[package]
name = "twertlefetch"
version = "1.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"
uname-rs = "0.1.1"
nix = "0.26.2"
devices = "0.3.0"
which = "4.4.0"
